baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Abraham's Photoblog"
theme                   = "hugo-theme-sam"
pygmentsStyle           = "manni"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    homepage            = "home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Abraham's Photoblog"

# Metadata
    description         = "Abraham's Photoblog"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/images/Abraham.jpg"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/post"
    text = "photoblog"

[[params.mainMenu]]
    link = "/gallery"
    text = "gallery"   

[[params.mainMenu]]
    link = "/about"
    text = "who is abraham?"

[[params.mainMenu]]
    link = "/categories"
    text = "categories"

[[params.mainMenu]]
    link = "/tags"
    text = "tags"